service: marketplace

plugins:
  - serverless-pseudo-parameters
  - serverless-cloudformation-sub-variables
  - serverless-s3-sync
  - serverless-build-client

custom:
  siteName: ${self:service}-ui-${opt:stage}
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: ui/build
  buildClient:
    packager: npm
    command: run build
    verbose: true

functions:
  bff:
    handler: .bff/build/lambda.handler
    memorySize: 4096
    environment:
      HELLO_WORLD: "YO"
    package:
      patterns:
        - ./bff/build/**
    condition: DeployBFF

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}
    STAGE: ${self:provider.stage}
  stackTags:
    Environment: ${self:provider.stage}
    Project: marketplace
    ServiceName: ${self:service}

resources:
  - Conditions:
      BuildAll: !Equals
        - "${env:BUILD_ALL, false}"
        - "true"
      BuildBFF: !Equals
        - "${env:BUILD_BFF, false}"
        - "true"
      DeployBFF: !Or
        - !Condition BuildAll
        - !Condition BuildBFF
  - ${file(./cf/s3.yml)}
  - ${file(./cf/cloudfront.yml)}