version: 2.1
defaults: &defaults
  working_directory: ~/repo
  executor:
    name: node/default

orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  check_changes:
    <<: *defaults
    steps:
      - checkout
      - run: cat > ~/repo/ci/new-env-vars
      - run: ~/repo/ci/check_for_changes.sh
      - run: cat ~/repo/ci/new-env-vars >> $BASH_ENV
      - run: git diff --name-only --diff-filter=AMDRT --cached
      - persist_to_workspace:
          root: ~/repo
          paths: .

  install_module_deps:
    <<: *defaults
    parameters:
      module:
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install-npm
      - restore_cache:
          keys:
            - << parameters.module >>-dependencies-{{ checksum "package.json" }}
            - << parameters.module >>-dependencies-
      - run: cd ./<< parameters.module >> && npm install
      - save_cache:
          paths:
            - node_modules
          key: << parameters.module >>-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: ./<< parameters.module >>/node_modules

  build:
    parameters:
      module:
        type: string
      createZip:
        type: boolean
        default: false
    environment:
      SCRIPT_ROOT: ./ci/<< parameters.module >>/build.sh
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: cat ~/repo/ci/new-env-vars >> $BASH_ENV
      - run: mkdir  ./<< parameters.module >>/build
      - run: $SCRIPT_ROOT
      - when:
          condition: << parameters.createZip >>
          steps:
            - run: mkdir  ./<< parameters.module >>/artifacts
            - run: zip -r ./<< parameters.module >>/artifacts/<< parameters.module >>.zip  ./<< parameters.module >>/build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./<< parameters.module >>/build
            - ./<< parameters.module >>/artifacts

  unit-test:
    parameters:
      module:
        type: string
    environment:
      SCRIPT_ROOT: ./ci/<< parameters.module >>/unit-test.sh
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: cat ~/repo/ci/new-env-vars >> $BASH_ENV
      - run: $SCRIPT_ROOT

  e2e-test:
    parameters:
      module:
        type: string
    environment:
      SCRIPT_ROOT: ./ci/<< parameters.module >>/e2e-test.sh
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: cat ~/repo/ci/new-env-vars >> $BASH_ENV
      - run: $SCRIPT_ROOT

  deploy:
    executor: aws-cli/default
    parameters:
      stage:
        default: dev
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: cat ~/repo/ci/new-env-vars >> $BASH_ENV
      - aws-cli/setup:
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
      - run: npm i
      - run: aws configure set region $AWS_DEFAULT_REGION --profile deployment
      - run: aws configure set profile.deployment.role_arn "$DEPLOYMENT_ROLE_ARN"
      - run: aws configure set profile.deployment.source_profile default
      - run:
          name: Get the correct params for deployment and deploy
          command: |
            params=( --stage << parameters.stage >> --aws-profile deployment)
            [[ $BUILD_BFF == true ]] && params+=(--nos3sync)
            npx serverless deploy "${params[@]}"

workflows:
  version: 2


  build_test_deploy:
    jobs:
      - check_changes
      - install_module_deps:
          name: "Install: BFF"
          module: bff
          requires:
            - check_changes
      - install_module_deps:
          name: "Install: UI"
          module: ui
          requires:
            - check_changes
      - build:
          name: "Build: BFF"
          module: bff
          createZip: true
          requires:
            - "Install: BFF"
      - build:
          name: "Build: UI"
          module: ui
          requires:
            - "Install: UI"
      - unit-test:
          name: "Test: UI UNIT"
          module: ui
          requires:
            - "Build: UI"
      - unit-test:
          name: "Test: BFF UNIT"
          module: bff
          requires:
            - "Build: BFF"
      - e2e-test:
          name: "Test: BFF E2E"
          module: bff
          requires:
            - "Build: BFF"
      - deploy:
          stage: dev
          name: "Deploy: DEV"
          context: org_ui
          filters:
            branches:
              only:
                - develop
          requires:
            - "Test: BFF UNIT"
            - "Test: BFF E2E"
            - "Test: UI UNIT"
      - deploy:
          stage: prod
          name: "Deploy: PROD"
          context: org_ui
          filters:
            branches:
              only:
                - master
          requires:
            - "Test: BFF UNIT"
            - "Test: BFF E2E"
            - "Test: UI UNIT"
      - deploy:
          stage: qa
          name: "Deploy: QA"
          context: org_ui
          filters:
            branches:
              only:
                - release/*
          requires:
            - "Test: BFF UNIT"
            - "Test: BFF E2E"
            - "Test: UI UNIT"
