query fetchProducts($brandIds: [String!], $pageInfo: PaginationInput) {
  catalog {
    products(input: { pageInfo: $pageInfo, filters: { brandIds: $brandIds } }) {
      name
      id
      Price {
        amount
        url
        currency
        site
      }
    }
  }
}
